### ISSUE TITLE
ReferenceError: that is not defined

### ISSUE THREAD

**Issue by hb0** [emersion/node-i2c-mpu6050#1]
After the most recent update I get the error aboth.
Just needed to add "var that = this;" after both lines 163 and 207 in your index.js

Thanks for publishing your implementation :-)

btw: Is there an option to increase the frequency of reading the sensor data?
When I use setInterval with 1ms I get an frequency of ~50Hz on my RPI.

**Comment by emersion** [comment]
Thanks!

According to the [datasheet](http://www.invensense.com/mems/gyro/documents/RM-MPU-6000A-00v4.2.pdf), it's possible to increase the sample rate (descriptor `SMPRT_DIV`), but I think that the pi is limiting the sample rate. What freq do you get when you read continuously the sensor data? You could get better perf if you read only data you need (e.g. not the temperature).

**Comment by hb0** [comment]
Thanks for the reply.

I receive a rate of 50Hz when I read continuously. I will try to leave out the temperature and check again.

**Comment by hb0** [comment]
Cool, that improved the frequency already to 55 Hz (without temperature) :-)
I will try around and see if I can increase the frequency a bit more.
