### ISSUE TITLE
npm package reports same rotation.x and rotation.z data

### ISSUE THREAD

**Issue by dannymyers** [emersion/node-i2c-mpu6050#4]
I noticed that the npm package is reporting the same data for x and z

"rotation":{**"x":-0.24416469749739667**,"y":-0.5005424817448549,**"z":-0.24416469749739667**}

**Comment by tobiasmuecksch** [comment]
Yep. I'm having the same issue...

**Comment by emersion** [comment]
Please fix it and send a PR.

**Comment by tobiasmuecksch** [comment]
@emersion I'm already looking into it. Will do.

**Comment by tobiasmuecksch** [comment]
@dannymyers @emersion After some research I found out, that you can't derive the Z rotation from the sensor readings of this gyroscope. The Z axis would give you the cardinal direction / orientation.  In case you need the Z axis you should buy a compass module.

This is discussed in the answer to this comment for example (you have to scroll down a bit to find it):
https://plus.google.com/118024096638328320339/posts/77dvxgR6KDe

I will create a pull request which removes the Z rotation reading to prevent future confusion.


===

@emersion The `i2c-bus` package is not in the package.json. Did you do that by decision?

**Comment by emersion** [comment]
>The i2c-bus package is not in the package.json. Did you do that by decision?

Yes, this module doesn't require `i2c-bus` per se. It could be used with another module offering the same interface for instance.

**Comment by tobiasmuecksch** [comment]
@emersion Okay that makes sense.
