### ISSUE TITLE
Unit of accelerometer values

### ISSUE THREAD

**Issue by dushyantbangal** [emersion/node-i2c-mpu6050#6]
What is the unit of the readings I'm getting for accelerometer?

In the code I see the values are being divided by `16384`. The datasheet says thats is the LSB Sensitivity for `±2g`. So is the unit `g`? Or is it m/s^2?

Do I change the constant `ACCEL_LSB_SENSITIVITY` if I want to use a different sensitivity?

**Comment by emersion** [comment]
You get g values, from -2g to +2g. If you want a different sensibility, you need to update `AFS_SEL` and the scale factor accordingly (the lib doesn't support changing that yet).
